const verbs = ["be", "have", "go", "do", "say", "make", "take", "see", "come",
    "know", "get", "give", "think", "tell", "work", "call", "try", "ask", "need",
    "feel", "become", "leave", "put", "mean", "keep", "let", "begin", "seem", "help",
    "talk", "turn", "start", "show", "hear", "play", "run", "move", "like", "live",
    "believe", "hold", "bring", "happen", "write", "sit", "stand", "lose", "pay",
    "meet", "include", "continue", "set", "change", "lead", "understand",
    "watch", "follow", "analyze", "budget", "collaborate", "delegate", "negotiate",
    "optimize", "prioritize", "strategize", "facilitate", "implement", "monitor",
    "coordinate", "evaluate", "generate", "integrate", "review", "play", "run",
    "jump", "write", "read", "monitor", "happen", "budget", 
    "accept", "allow", "answer", "arrive", "bake", "believe", "borrow", "call", 
    "clean", "climb", "close", "compare", "cook", "dance", "deliver", "describe", 
    "develop", "discover", "divide", "dress", "drop", "enjoy", "enter", "explain", 
    "finish", "follow", "happen", "help", "hope", "imagine", "improve", "include", 
    "invent", "invite", "join", "jump", "laugh", "learn", "listen", "love", "move", 
    "need", "open", "paint", "pull", "push", "rain", "remember", "repeat",
    "act", "add", "agree", "allow", "appear", "apply", "argue", "avoid", "base",
    "bathe", "behave", "blame", "bless", "boil", "bow", "break", "breathe",
    "build", "burn", "bury", "buy", "catch", "challenge", "charge", "chase",
    "check", "claim", "click", "collect", "combine", "command", "communicate",
    "compete", "complete", "consider", "contain", "contribute", "control",
    "convert", "copy", "create", "cut", "damage", "decide", "decorate",
    "define", "demand", "deny", "depend", "design", "destroy", "determine",
    "differ", "direct", "disagree", "disappear", "discuss", "display",
    "distribute", "draw", "dream", "drink", "drive", "earn", "educate", "employ",
    "encourage", "end", "engage", "enjoy", "ensure", "establish", "estimate",
    "examine", "exchange", "excuse", "exercise", "exist", "expand", "expect",
    "experience", "experiment", "explode", "express", "extend", "face", "fail",
    "fall", "fasten", "fear", "feed", "fight", "fill", "find", "fire", "fix",
    "fly", "fold", "forget", "forgive", "form", "found", "freeze", "fry",
    "gather", "glow", "grant", "guard", "guess", "guide", "hang", "harm",
    "hate", "have", "head", "heal", "hide", "hit", "hug", "hunt", "hurry",
    "identify", "ignore", "illustrate", "imagine", "imitate", "import",
    "impress", "improve", "increase", "influence", "inform", "inject",
    "injure", "inspire", "install", "intend", "interest", "interfere",
    "interrupt", "introduce", "invent", "invest", "investigate", "invite",
    "judge", "jump", "justify", "kick", "kill", "kiss", "kneel", "knit",
    "knock", "knot", "label", "land", "last", "laugh", "launch", "lay",
    "lead", "lean", "leap", "learn", "leave", "lend", "let", "lie", "lift",
    "light", "like", "list", "listen", "live", "load", "lock", "log", "look",
    "lose", "love", "maintain", "make", "manage", "march", "mark", "marry",
    "match", "mate", "matter", "measure", "meddle", "meet", "melt", "memorize",
    "mend", "mention", "mess", "milk", "mine", "miss", "mix", "moan", "moor",
    "mourn", "move", "muddle", "mug", "multiply", "murmur", "nail", "name",
    "need", "nest", "nod", "note", "notice", "number", "obey", "object",
    "observe", "obtain", "occur", "offend", "offer", "open", "operate",
    "order", "organize", "overflow", "owe", "own", "pack", "paddle", "paint",
    "park", "part", "pass", "paste", "pat", "pause", "pay", "peck", "pedal",
    "peel", "peep", "perform", "permit", "persuade", "phone", "pick",
    "pinch", "pine", "place", "plan", "plant", "play", "plead", "please",
    "plug", "point", "poke", "polish", "pop", "possess", "post", "pour",
    "practice", "praise", "pray", "preach", "precede", "predict", "prefer",
    "prepare", "prescribe", "present", "preserve", "press", "pretend",
    "prevent", "print", "produce", "program", "promise", "protect", "provide",
    "pull", "pump", "punch", "puncture", "punish", "push", "question",
    "queue", "race", "radiate", "rain", "raise", "reach", "realize", "receive",
    "recognize", "record", "reduce", "reflect", "refuse", "regret", "reign",
    "reject", "rejoice", "relax", "release", "rely", "remain", "remember",
    "remind", "remove", "repair", "repeat", "replace", "reply", "report",
    "represent", "reproduce", "request", "rescue", "research", "resolve",
    "respect", "rest", "restrain", "retire", "retrieve", "return", "reveal",
    "revolve", "reward", "risk", "rob", "rock", "roll", "rot", "rub", "ruin",
    "rule", "rush", "sack", "sail", "satisfy", "save", "saw", "scare",
    "scatter", "scold", "scorch", "scrape", "scratch", "scream", "screw",
    "scribble", "scrub", "seal", "search", "secure", "see", "seek", "select",
    "sell", "send", "sense", "separate", "serve", "set", "settle", "shake",
    "share", "shave", "shelter", "shine", "shiver", "shock", "shop", "shout",
    "show", "shrink", "shut", "sigh", "sign", "signal", "sin", "sing", "sink",
    "sip", "sit", "sketch", "ski", "skip", "slap", "slay", "sleep", "slide",
    "slip", "slow", "smash", "smell", "smile", "smoke", "snatch", "sneak",
    "sneeze", "sniff", "snore", "snow", "soak", "soothe", "sound", "spare",
    "spark", "sparkle", "speak", "specify", "speed", "spell", "spend", "spill",
    "spin", "spit", "split", "spoil", "spot", "spray", "spread", "spring",
    "sprout", "squash", "squeak", "squeal", "squeeze", "stain", "stamp",
    "stand", "stare", "start", "stay", "steal", "steer", "step", "stick",
    "stimulate", "sting", "stink", "stir", "stitch", "stop", "store", "strap",
    "stray", "stress", "stretch", "stride", "strike", "string", "strip",
    "stroke", "stuff", "stumble", "stutter", "subtract", "succeed", "suck",
    "suffer", "suggest", "suit", "supply", "support", "suppose", "surprise",
    "surround", "suspect", "suspend", "swear", "sweat", "sweep", "swell",
    "swim", "swing", "switch", "sympathize", "take", "talk", "tame", "tap",
    "taste", "teach", "tear", "tease", "telephone", "tell", "tempt", "terrify",
    "test", "thank", "thaw", "think", "threaten", "throw", "thrust", "tick",
    "tickle", "tie", "time", "tip", "tire", "touch", "tour", "tow", "trace",
    "trade", "train", "transcribe", "transform", "translate", "transport",
    "trap", "travel", "tread", "treat", "tremble", "trick", "trigger",
    "trim", "trip", "trot", "trouble", "trust", "try", "tug", "tumble",
    "tune", "turn", "tutor", "twist", "type", "understand", "undress",
    "unfasten", "unify", "unite", "unlock", "unpack", "unscrew", "use",
    "usher", "vacuum", "value", "vanish", "vary", "venture", "visit", "wail",
    "wait", "wake", "walk", "wander", "want", "warm", "warn", "wash", "waste",
    "watch", "water", "wave", "wear", "weave", "wed", "weep", "weigh",
    "welcome", "whine", "whip", "whirl", "whisper", "whistle", "win", "wind",
    "wink", "wipe", "wish", "withdraw", "wobble", "wonder", "work", "worry",
    "wrap", "wreck", "wrestle", "wring", "write", "yawn", "yell", "zip", "zoom"];

export default verbs;